// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20191102072437_CreateDb")]
    partial class CreateDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("Domain.Reply", b =>
                {
                    b.Property<int>("replyId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("creationDT");

                    b.Property<int>("posterId");

                    b.Property<string>("replyContent");

                    b.HasKey("replyId");

                    b.ToTable("posts");
                });

            modelBuilder.Entity("Domain.Thread", b =>
                {
                    b.Property<int>("threadId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("creationDT");

                    b.Property<string>("postContent");

                    b.Property<int>("posterId");

                    b.HasKey("threadId");

                    b.ToTable("threads");
                });

            modelBuilder.Entity("Domain.User", b =>
                {
                    b.Property<int>("userId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("creationDate");

                    b.Property<string>("username");

                    b.HasKey("userId");

                    b.ToTable("users");
                });
#pragma warning restore 612, 618
        }
    }
}
